services:
  app:
    build:
      context: ../../../../../..
      dockerfile: src/instrumentation/libraries/upstash-redis-js/e2e-tests/esm-upstash-redis-js/Dockerfile
      args:
        - CACHEBUST=${CACHEBUST:-1}
        - TUSK_CLI_VERSION=${TUSK_CLI_VERSION:-latest}
    environment:
      - PORT=3000
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
      - TUSK_ANALYTICS_DISABLED=1
      - BENCHMARKS=${BENCHMARKS:-}
      - BENCHMARK_DURATION=${BENCHMARK_DURATION:-30}
      - BENCHMARK_WARMUP=${BENCHMARK_WARMUP:-3}
    volumes:
      - ../../../../../..:/sdk:ro
      - ./.tusk/config.yaml:/app/.tusk/config.yaml:ro
      - ./src:/app/src
    working_dir: /app
